spring.application.name=connectify

spring.datasource.url=jdbc:mysql://localhost:3306/connectify_db 
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8085
//??nh ngh?a domain c?a ?ng d?ng (Khi lên deploy th?t b?n ch? c?n ??i dòng này)/
app.base-url=http://localhost:${server.port}

---------Mail-------------
# C?u hình SMTP Server c?a Gmail
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=7644d4f768071e

# M?t kh?u ?ng d?ng (App Password), KHÔNG PH?I m?t kh?u ??ng nh?p Gmail thông th??ng
spring.mail.password=42d8d9c5df6843

# Các c?u hình b?o m?t b?t bu?c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true